matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      services:
        - xvfb
      before_install:
        - sudo apt-get install -y xclip;
      after_install:
        - export FrameworkPathOverride=/usr/lib/mono/4.7.2-api/
        - sudo cp /usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.WinFx.props /usr/share/dotnet/sdk/3.1.201/Sdks/Microsoft.NET.Sdk.WindowsDesktop/targets/Microsoft.WinFX.props
    - os: osx
      sudo: required
      after_install:
        - export FrameworkPathOverride=/Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/4.7.2-api/

android:
  components:
    - android-30
mono: latest
language: csharp
dotnet: 3.1.201
script:
  - nuget install NUnit.Console -Version 3.11.1 -OutputDirectory testrunner
  - msbuild src/TextCopy.sln /t:restore /p:Configuration=Release -verbosity:quiet
  - msbuild src/TextCopy.sln /t:build /p:Configuration=Release -verbosity:quiet
  - dotnet test src/Tests/Tests.csproj --configuration Release --framework netcoreapp3.1 --no-build --no-restore
  - mono ./testrunner/NUnit.ConsoleRunner.3.11.1/tools/nunit3-console.exe ./src/Tests/bin/Release/net472/Tests.dll