image:
- Visual Studio 2019
- macos
skip_commits:
  message: /doco|Merge pull request.*/
test: off
artifacts:
- path: nugets\*.nupkg
for:
-
  matrix:
    only:
      - image: macos

  build_script:
  - ps: src/build.ps1
-
  matrix:
    only:
      - image: Visual Studio 2019

  build_script:
  - ps: src/build.ps1