image:
- Ubuntu2004
- Visual Studio 2019
- macos
skip_commits:
  message: /doco|Merge pull request.*/
test: off
artifacts:
- path: nugets\*.nupkg
for:
-
  matrix:
    only:
      - image: macos

  build_script:
  - ps: src/build-macos.ps1
-
  matrix:
    only:
      - image: Visual Studio 2019

  build_script:
  - ps: src/build-win.ps1
-
  matrix:
    only:
      - image: Ubuntu2004
  addons:
    apt:
      packages:
        - xvfb
  install:
  - sh: >
      sudo apt-get install -y xclip
      export DISPLAY=<x11-server-ip>:0
  build_script:
  - ps: src/build-linux.ps1